### ISSUE TITLE
Cannot restart the container because executable path gets concatenated to itself

### ISSUE THREAD

**Issue by jstarrdewar** [clearent/nexus#1]
I'm trying to figure out why this is happening but I haven't tried to use Docker before so there might be something obvious I'm overlooking. I'm on an Amazon t2.small instance.

Steps to reproduce:

- install container (it runs fine; able to access web interface)
- run `docker stop nexus`
- run `docker start nexus`
- Process doesn't restart. Following error message shows up in logs. `docker logs -f nexus`

```
Error occurred shutting down framework: java.lang.IllegalArgumentException: Invalid karaf.home system property '/opt/nexus-3.0.1-01opt/nexus-3.0.1-01' : does not existjava.lang.IllegalArgumentException: Invalid karaf.home system property '/opt/nexus-3.0.1-01opt/nexus-3.0.1-01' : does not exist
        at org.apache.karaf.main.util.Utils.validateDirectoryExists(Utils.java:86)
        at org.apache.karaf.main.util.Utils.getKarafHome(Utils.java:37)
        at org.apache.karaf.main.ConfigProperties.<init>(ConfigProperties.java:182)
        at org.apache.karaf.main.Main.updateInstancePidAfterShutdown(Main.java:224)
        at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:63)
```

**Comment by cavemandaveman** [comment]
Looks like there was an error in the entrypoint script. `.` is a reserved character for `sed` so I had to change some logic. Thanks for catching that!

If you rebuild or pull the image from docker hub again, it will work as expected.
